-- Run this migration in the Supabase SQL editor or with the Supabase CLI.
create table if not exists public.waitlist (
  id bigint generated by default as identity primary key,
  email text not null,
  source text not null default 'landing-page',
  created_at timestamptz not null default now(),
  constraint waitlist_email_length check (char_length(email) between 3 and 254)
);

create unique index if not exists waitlist_email_unique_idx
  on public.waitlist (lower(email));

alter table public.waitlist enable row level security;

-- Intentionally create no public policies. Inserts go through the server-only API
-- route using SUPABASE_SERVICE_ROLE_KEY, keeping the table inaccessible to clients.
comment on table public.waitlist is 'Private early-access signups collected by the Subframe landing page.';
